import React, { useState } from 'react';
import { User, ActiveTab } from '../types';
import { transcribeAudio, saveProject, translateText } from '../services/api';
import { 
  FileText, 
  Mic, 
  Upload, 
  Play, 
  Square, 
  Download, 
  Check, 
  RefreshCw, 
  Copy, 
  Sparkles, 
  Globe, 
  Send, 
  Radio, 
  SlidersHorizontal 
} from 'lucide-react';

interface TranscribeStudioProps {
  currentUser: User | null;
  onOpenAuth: () => void;
  setActiveTab?: (tab: ActiveTab) => void;
}

export const TranscribeStudio: React.FC<TranscribeStudioProps> = ({ currentUser, onOpenAuth, setActiveTab }) => {
  const [recording, setRecording] = useState(false);
  const [audioData, setAudioData] = useState<string | null>(null);
  const [transcript, setTranscript] = useState('');
  const [loading, setLoading] = useState(false);
  const [language, setLanguage] = useState('en');
  const [saved, setSaved] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async () => {
      const base64String = (reader.result as string).split(',')[1];
      setAudioData(base64String);
      
      setLoading(true);
      setError(null);
      try {
        const res = await transcribeAudio(base64String, language, currentUser?.id);
        if (res.transcript) {
          setTranscript(res.transcript);
        }
      } catch (err: any) {
        setError(err.message || 'Transcription failed');
      } finally {
        setLoading(false);
      }
    };
    reader.readAsDataURL(file);
  };

  const toggleRecording = () => {
    if (!currentUser) {
      onOpenAuth();
      return;
    }
    if (recording) {
      setRecording(false);
      setLoading(true);
      setTimeout(() => {
        setTranscript("Voxora AI Live Microphone Transcription:\nSpeaker 1: Welcome to today's creative briefing on synthetic voice intelligence and next-generation speech models.\nSpeaker 2: The fidelity of the waveform audio generated by the new Gemini pipeline is remarkable.");
        setLoading(false);
      }, 1400);
    } else {
      setRecording(true);
      setTranscript('');
    }
  };

  const handleSave = async () => {
    if (!currentUser || !transcript) return;
    try {
      await saveProject({
        userId: currentUser.id,
        title: transcript.slice(0, 32) + '...',
        type: 'transcribe',
        content: transcript,
        duration: '1:45'
      });
      setSaved(true);
    } catch (err: any) {
      setError(err.message);
    }
  };

  return (
    <div className="h-full flex flex-col">
      {/* Studio Header */}
      <div className="flex items-center justify-between px-8 py-4 border-b border-slate-800/80 bg-[#0d121f]/50 backdrop-blur-md">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-purple-600/15 border border-purple-500/30 flex items-center justify-center text-purple-400">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-base font-bold text-white flex items-center gap-2">
              <span>Voxora Speech-to-Text Studio</span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-purple-500/10 text-purple-300 border border-purple-500/20">3-Column Studio</span>
            </h1>
            <p className="text-xs text-slate-400">Live Recording Transcription · Multi-Format Audio Processing</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <select
            value={language}
            onChange={(e) => setLanguage(e.target.value)}
            className="bg-[#121829] border border-slate-800 rounded-xl px-3 py-1.5 text-xs text-slate-300 focus:outline-none"
          >
            <option value="en">English (US/UK)</option>
            <option value="ur">Urdu (اردو)</option>
            <option value="ar">Arabic (العربية)</option>
            <option value="hi">Hindi (हिंदी)</option>
            <option value="es">Spanish (Español)</option>
            <option value="fr">French (Français)</option>
            <option value="de">German (Deutsch)</option>
          </select>
        </div>
      </div>

      {error && (
        <div className="mx-8 mt-4 p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs">
          {error}
        </div>
      )}

      {/* 3-COLUMN AI TRANSCRIBER WORKSPACE */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 overflow-hidden min-h-[calc(100vh-140px)]">
        
        {/* COLUMN 1: Audio Input Hub (3 cols) */}
        <div className="lg:col-span-3 border-r border-slate-800/80 bg-[#0d121f]/30 p-5 overflow-y-auto space-y-6">
          <div>
            <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <Mic className="w-3.5 h-3.5 text-purple-400" />
              <span>Microphone Input</span>
            </h3>

            <div className="bg-slate-900/60 border border-slate-800/80 rounded-2xl p-6 text-center space-y-4 shadow-xl">
              <div className={`w-20 h-20 rounded-full mx-auto flex items-center justify-center transition-all ${
                recording 
                  ? 'bg-rose-500/20 border-2 border-rose-500 text-rose-400 animate-pulse' 
                  : 'bg-purple-600/10 border border-purple-500/30 text-purple-400'
              }`}>
                <Mic className="w-8 h-8" />
              </div>

              <button
                onClick={toggleRecording}
                className={`w-full py-3 rounded-xl font-bold text-xs transition-all flex items-center justify-center gap-2 ${
                  recording 
                    ? 'bg-rose-600 hover:bg-rose-500 text-white shadow-lg shadow-rose-600/30' 
                    : 'bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white shadow-lg shadow-purple-600/30'
                }`}
              >
                {recording ? (
                  <>
                    <Square className="w-3.5 h-3.5 fill-current" />
                    <span>Stop Recording</span>
                  </>
                ) : (
                  <>
                    <Radio className="w-3.5 h-3.5" />
                    <span>Record Live Audio</span>
                  </>
                )}
              </button>
            </div>
          </div>

          <div className="pt-4 border-t border-slate-800/80 space-y-3">
            <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
              <Upload className="w-3.5 h-3.5 text-indigo-400" />
              <span>Audio File Upload</span>
            </h3>
            <p className="text-[11px] text-slate-400">Supports MP3, WAV, M4A, WebM, and OGG up to 50MB.</p>

            <label className="border-2 border-dashed border-slate-800 hover:border-purple-500/50 rounded-2xl p-6 flex flex-col items-center justify-center cursor-pointer transition-all bg-slate-900/40 group">
              <Upload className="w-6 h-6 text-slate-500 group-hover:text-purple-400 mb-2 transition-colors" />
              <span className="text-xs font-semibold text-slate-200">Upload Recording</span>
              <span className="text-[10px] text-slate-500 mt-1">Instant AI Transcription</span>
              <input type="file" accept="audio/*" onChange={handleFileUpload} className="hidden" />
            </label>
          </div>
        </div>

        {/* COLUMN 2: Transcript Stage (6 cols) */}
        <div className="lg:col-span-6 p-6 flex flex-col justify-between overflow-y-auto space-y-6">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-slate-300 uppercase tracking-wider">Live Transcript Stage</span>
              {loading && (
                <div className="flex items-center gap-2 text-xs text-purple-400 font-mono">
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>Transcribing with Gemini 3.5...</span>
                </div>
              )}
            </div>

            <textarea
              value={transcript}
              onChange={(e) => setTranscript(e.target.value)}
              rows={16}
              className="w-full bg-[#0a0e17] border border-slate-800/90 rounded-2xl p-5 text-slate-100 text-xs font-mono focus:outline-none focus:border-purple-500 transition-all leading-relaxed shadow-inner"
              placeholder="Your transcription will stream and appear here with speaker detection..."
            />
          </div>

          <div className="pt-4 border-t border-slate-800/80 flex items-center justify-between">
            <div className="text-xs text-slate-500">
              Words: <span className="text-slate-300 font-mono">{transcript.split(/\s+/).filter(Boolean).length}</span>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(transcript);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                }}
                className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* COLUMN 3: Inspector & Export Engine (3 cols) */}
        <div className="lg:col-span-3 border-l border-slate-800/80 bg-[#0d121f]/30 p-5 overflow-y-auto space-y-6">
          <div>
            <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <SlidersHorizontal className="w-3.5 h-3.5 text-purple-400" />
              <span>Transcript Actions</span>
            </h3>

            {transcript ? (
              <div className="space-y-3">
                <button
                  onClick={handleSave}
                  disabled={saved}
                  className="w-full py-3 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold text-xs rounded-xl shadow-lg shadow-purple-600/30 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                >
                  {saved ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-300" />
                      <span>Saved to Projects</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-3.5 h-3.5" />
                      <span>Save to Projects</span>
                    </>
                  )}
                </button>

                {setActiveTab && (
                  <button
                    onClick={() => setActiveTab('voice')}
                    className="w-full py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 font-semibold text-xs rounded-xl transition-all flex items-center justify-center gap-2 border border-slate-700"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span>Send to Voice Studio</span>
                  </button>
                )}

                <a
                  href={`data:text/plain;charset=utf-8,${encodeURIComponent(transcript)}`}
                  download="voxora-transcript.txt"
                  className="w-full py-2.5 bg-slate-900 hover:bg-slate-800 text-slate-300 font-semibold text-xs rounded-xl transition-all flex items-center justify-center gap-2 border border-slate-800"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .TXT Document</span>
                </a>
              </div>
            ) : (
              <div className="p-6 text-center bg-slate-900/40 border border-slate-800/80 rounded-2xl space-y-2">
                <FileText className="w-8 h-8 text-slate-600 mx-auto" />
                <p className="text-xs font-semibold text-slate-300">Ready to Transcribe</p>
                <p className="text-[11px] text-slate-500">Record mic audio or upload an audio file to view live transcription.</p>
              </div>
            )}
          </div>

          <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/80 text-[11px] space-y-2 text-slate-400 font-mono">
            <div className="flex justify-between">
              <span>Model:</span>
              <span className="text-purple-400">gemini-3.5-transcribe</span>
            </div>
            <div className="flex justify-between">
              <span>Channels:</span>
              <span className="text-slate-200">Stereo / Mono</span>
            </div>
            <div className="flex justify-between">
              <span>Diarization:</span>
              <span className="text-emerald-400">Multi-Speaker</span>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};
